apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ml-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 172.16.100.10:30500/ml-platform/frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: API_UPSTREAM
              value: http://backend.ml-test.svc.cluster.local:8080
            - name: MLFLOW_UPSTREAM
              value: http://mlflow.ml-test.svc.cluster.local:5000
            - name: KEYCLOAK_UPSTREAM
              value: http://keycloak.ml-test.svc.cluster.local:8080
            - name: JUPYTERHUB_UPSTREAM
              value: http://ml-test-jupyterhub-proxy-public.ml-test.svc.cluster.local:80
            - name: RUNTIME_API_URL
              value: /api/v1
            - name: RUNTIME_KEYCLOAK_URL
              value: ""
            - name: RUNTIME_KEYCLOAK_REALM
              value: ml-platform
            - name: RUNTIME_KEYCLOAK_CLIENT_ID
              value: ml-platform-portal
            - name: RUNTIME_ENABLE_OIDC
              value: "true"
          volumeMounts:
            - name: frontend-nginx-template
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: frontend-nginx-template
          configMap:
            name: frontend-nginx-template
