apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: __NAMESPACE__
spec:
  type: __FRONTEND_SERVICE_TYPE__
  __LOADBALANCER_IP__
  selector:
    app: frontend
  ports:
    - name: http
      port: __HTTP_PORT__
      targetPort: http
      __NODEPORT_LINE__
    __TLS_SERVICE_PORT__
