apiVersion: v1
kind: Secret
metadata:
  name: kserve-s3-secret
  namespace: __NAMESPACE__
  annotations:
    serving.kserve.io/s3-endpoint: __S3_ENDPOINT_HOST__
    serving.kserve.io/s3-usehttps: "__S3_USE_HTTPS__"
    serving.kserve.io/s3-region: __S3_REGION__
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: __S3_ACCESS_KEY__
  AWS_SECRET_ACCESS_KEY: __S3_SECRET_KEY__
