apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/part-of: ml-platform
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: __S3_ACCESS_KEY__
  AWS_SECRET_ACCESS_KEY: __S3_SECRET_KEY__
  # Keys used by the Container Registry (registry:2 Docker Distribution)
  endpoint: __S3_ENDPOINT__
  access-key: __S3_ACCESS_KEY__
  secret-key: __S3_SECRET_KEY__
