apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  BACKEND_STORE_URI: {{ .Values.mlflow.backendStoreUri | quote }}
  MLFLOW_DEFAULT_ARTIFACT_ROOT: {{ .Values.mlflow.artifactRoot | quote }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.mlflow.s3EndpointUrl | quote }}
  MLFLOW_S3_IGNORE_TLS: {{ .Values.mlflow.s3IgnoreTls | quote }}
