apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-platform
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://172.16.100.10:30080/realms/ml-platform
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://keycloak.ml-platform.svc.cluster.local:8080/realms/ml-platform/protocol/openid-connect/certs
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "4"
              memory: 4Gi
