apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        hub.jupyter.org/network-access-hub: "true"
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: ml-platform-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SERVICES_MLFLOW_TRACKING_URL
              value: /mlflow
            - name: JUPYTERHUB_API_TOKEN
              value: platform-api-service-token
            - name: WORKSPACE_DEFAULT_NOTEBOOK
              value: sample-delta-data.ipynb
            - name: APP_CORS_ALLOWED_ORIGINS
              value: http://localhost:4200,http://localhost:8080,http://localhost:30080,http://192.168.64.2:30080,http://172.16.100.10:30080,https://portal.ml-platform.local
            - name: SERVICES_KSERVE_DEPLOYMENT_MODE
              value: Standard
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
