apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-serviceaccount.yaml
  - backend-rbac.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-nginx-template-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - registry-deployment.yaml
  - registry-service.yaml
  - registry-credentials-secret.yaml
  - kaniko-rbac.yaml
  - jupyterlab-config-configmap.yaml
