apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: ml-platform
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
