apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: ml-platform
  labels:
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin
  endpoint: http://minio.ml-platform.svc:9000
