spring:
  application:
    name: ml-platform-backend
  datasource:
    url: jdbc:postgresql://postgresql.ml-platform.svc:5432/ml_platform
    username: postgres
    password: localdevpassword
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ml-platform.svc:8080/realms/ml-platform
          jwk-set-uri: http://keycloak.ml-platform.svc:8080/realms/ml-platform/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: https://portal.ml-platform.local

workspace:
  default-notebook: ${WORKSPACE_DEFAULT_NOTEBOOK:getting-started.ipynb}

services:
  jupyterhub:
    url: http://jupyterhub-hub.ml-platform.svc:8081
    api-token: ${JUPYTERHUB_API_TOKEN:ml-platform-jupyterhub-token}
  mlflow:
    url: http://mlflow.ml-platform.svc:5000
    tracking-url: http://mlflow.ml-platform.svc:5000
  airflow:
    url: http://airflow-webserver.ml-platform.svc:8080
    username: admin
    password: admin
  kserve:
    namespace: ml-platform-serving
    service-account-name: kserve-s3-sa
    model-format-name: mlflow
    runtime-name: kserve-mlserver
    mock-enabled: false
  minio:
    endpoint: http://minio.ml-platform.svc:9000
    access-key: minioadmin
    secret-key: minioadmin
    pipelines-bucket: ml-platform-pipelines
    presign-expiry-seconds: 900
