spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ml_platform
    username: postgres
    password: localdevpassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ml-platform
          jwk-set-uri: http://localhost:8180/realms/ml-platform/protocol/openid-connect/certs

app:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:8080

services:
  jupyterhub:
    url: http://localhost:8181
    proxy-url: http://localhost:8181
    public-url: http://localhost:8181
    api-token: ml-platform-jupyterhub-token
  mlflow:
    url: http://localhost:15000
    tracking-url: http://localhost:15000
  airflow:
    url: http://localhost:8280
    username: admin
    password: admin
  kserve:
    namespace: ml-platform-serving
    service-account-name: kserve-s3-sa
    model-format-name: sklearn
    runtime-name: kserve-sklearnserver
    deployment-mode: Standard
    kubeconfig-path: ${KUBECONFIG_PATH:${user.home}/.kube/config}
    kube-context: ${KUBECONFIG_CONTEXT:local}
    mock-enabled: false
  minio:
    endpoint: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin
    pipelines-bucket: ml-platform-pipelines
    presign-expiry-seconds: 900
