spring:
  datasource:
    url: jdbc:h2:mem:ml-platform;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ml-platform

app:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:8080

workspace:
  default-notebook: examples/sample-delta-data.ipynb

services:
  jupyterhub:
    url: https://jupyter.example.invalid
    api-token: dev-token
  mlflow:
    url: https://mlflow-api.example.invalid
    tracking-url: https://mlflow-ui.example.invalid
  airflow:
    url: https://airflow-api.example.invalid
    username: dev-admin
    password: dev-admin
    mock-enabled: true
  kserve:
    namespace: ml-platform-serving
    service-account-name: kserve-s3-sa
    model-format-name: sklearn
    runtime-name: kserve-sklearnserver
    deployment-mode: Standard
    mock-enabled: true
  minio:
    endpoint: https://minio.example.invalid
    access-key: dev-access
    secret-key: dev-secret
    pipelines-bucket: ml-platform-pipelines
    presign-expiry-seconds: 900
